/**
 * 한국인 여행 도시 DB 시드 스크립트
 * 국가 50개 / 도시 485개
 * 실행: npx ts-node prisma/seed-cities.ts
 */
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌍 도시 DB 시드 시작...')

  // ── 1. 국가 upsert (code @unique 활용) ─────────────────────────
  await prisma.$transaction([
    prisma.country.upsert({ where: { code: 'AE' }, update: { nameKo: '아랍에미리트', nameEn: 'United Arab Emirates' }, create: { code: 'AE', nameKo: '아랍에미리트', nameEn: 'United Arab Emirates' } }),
    prisma.country.upsert({ where: { code: 'AT' }, update: { nameKo: '오스트리아', nameEn: 'Austria' }, create: { code: 'AT', nameKo: '오스트리아', nameEn: 'Austria' } }),
    prisma.country.upsert({ where: { code: 'AU' }, update: { nameKo: '호주', nameEn: 'Australia' }, create: { code: 'AU', nameKo: '호주', nameEn: 'Australia' } }),
    prisma.country.upsert({ where: { code: 'BE' }, update: { nameKo: '벨기에', nameEn: 'Belgium' }, create: { code: 'BE', nameKo: '벨기에', nameEn: 'Belgium' } }),
    prisma.country.upsert({ where: { code: 'BR' }, update: { nameKo: '브라질', nameEn: 'Brazil' }, create: { code: 'BR', nameKo: '브라질', nameEn: 'Brazil' } }),
    prisma.country.upsert({ where: { code: 'CA' }, update: { nameKo: '캐나다', nameEn: 'Canada' }, create: { code: 'CA', nameKo: '캐나다', nameEn: 'Canada' } }),
    prisma.country.upsert({ where: { code: 'CH' }, update: { nameKo: '스위스', nameEn: 'Switzerland' }, create: { code: 'CH', nameKo: '스위스', nameEn: 'Switzerland' } }),
    prisma.country.upsert({ where: { code: 'CN' }, update: { nameKo: '중국', nameEn: 'China' }, create: { code: 'CN', nameKo: '중국', nameEn: 'China' } }),
    prisma.country.upsert({ where: { code: 'CU' }, update: { nameKo: '쿠바', nameEn: 'Cuba' }, create: { code: 'CU', nameKo: '쿠바', nameEn: 'Cuba' } }),
    prisma.country.upsert({ where: { code: 'CZ' }, update: { nameKo: '체코', nameEn: 'Czech Republic' }, create: { code: 'CZ', nameKo: '체코', nameEn: 'Czech Republic' } }),
    prisma.country.upsert({ where: { code: 'DE' }, update: { nameKo: '독일', nameEn: 'Germany' }, create: { code: 'DE', nameKo: '독일', nameEn: 'Germany' } }),
    prisma.country.upsert({ where: { code: 'EG' }, update: { nameKo: '이집트', nameEn: 'Egypt' }, create: { code: 'EG', nameKo: '이집트', nameEn: 'Egypt' } }),
    prisma.country.upsert({ where: { code: 'ES' }, update: { nameKo: '스페인', nameEn: 'Spain' }, create: { code: 'ES', nameKo: '스페인', nameEn: 'Spain' } }),
    prisma.country.upsert({ where: { code: 'FI' }, update: { nameKo: '핀란드', nameEn: 'Finland' }, create: { code: 'FI', nameKo: '핀란드', nameEn: 'Finland' } }),
    prisma.country.upsert({ where: { code: 'FR' }, update: { nameKo: '프랑스', nameEn: 'France' }, create: { code: 'FR', nameKo: '프랑스', nameEn: 'France' } }),
    prisma.country.upsert({ where: { code: 'GB' }, update: { nameKo: '영국', nameEn: 'United Kingdom' }, create: { code: 'GB', nameKo: '영국', nameEn: 'United Kingdom' } }),
    prisma.country.upsert({ where: { code: 'GR' }, update: { nameKo: '그리스', nameEn: 'Greece' }, create: { code: 'GR', nameKo: '그리스', nameEn: 'Greece' } }),
    prisma.country.upsert({ where: { code: 'HK' }, update: { nameKo: '홍콩', nameEn: 'Hong Kong' }, create: { code: 'HK', nameKo: '홍콩', nameEn: 'Hong Kong' } }),
    prisma.country.upsert({ where: { code: 'HR' }, update: { nameKo: '크로아티아', nameEn: 'Croatia' }, create: { code: 'HR', nameKo: '크로아티아', nameEn: 'Croatia' } }),
    prisma.country.upsert({ where: { code: 'HU' }, update: { nameKo: '헝가리', nameEn: 'Hungary' }, create: { code: 'HU', nameKo: '헝가리', nameEn: 'Hungary' } }),
    prisma.country.upsert({ where: { code: 'ID' }, update: { nameKo: '인도네시아', nameEn: 'Indonesia' }, create: { code: 'ID', nameKo: '인도네시아', nameEn: 'Indonesia' } }),
    prisma.country.upsert({ where: { code: 'IN' }, update: { nameKo: '인도', nameEn: 'India' }, create: { code: 'IN', nameKo: '인도', nameEn: 'India' } }),
    prisma.country.upsert({ where: { code: 'IS' }, update: { nameKo: '아이슬란드', nameEn: 'Iceland' }, create: { code: 'IS', nameKo: '아이슬란드', nameEn: 'Iceland' } }),
    prisma.country.upsert({ where: { code: 'IT' }, update: { nameKo: '이탈리아', nameEn: 'Italy' }, create: { code: 'IT', nameKo: '이탈리아', nameEn: 'Italy' } }),
    prisma.country.upsert({ where: { code: 'JO' }, update: { nameKo: '요르단', nameEn: 'Jordan' }, create: { code: 'JO', nameKo: '요르단', nameEn: 'Jordan' } }),
    prisma.country.upsert({ where: { code: 'JP' }, update: { nameKo: '일본', nameEn: 'Japan' }, create: { code: 'JP', nameKo: '일본', nameEn: 'Japan' } }),
    prisma.country.upsert({ where: { code: 'KG' }, update: { nameKo: '키르기스스탄', nameEn: 'Kyrgyzstan' }, create: { code: 'KG', nameKo: '키르기스스탄', nameEn: 'Kyrgyzstan' } }),
    prisma.country.upsert({ where: { code: 'KH' }, update: { nameKo: '캄보디아', nameEn: 'Cambodia' }, create: { code: 'KH', nameKo: '캄보디아', nameEn: 'Cambodia' } }),
    prisma.country.upsert({ where: { code: 'KZ' }, update: { nameKo: '카자흐스탄', nameEn: 'Kazakhstan' }, create: { code: 'KZ', nameKo: '카자흐스탄', nameEn: 'Kazakhstan' } }),
    prisma.country.upsert({ where: { code: 'LA' }, update: { nameKo: '라오스', nameEn: 'Laos' }, create: { code: 'LA', nameKo: '라오스', nameEn: 'Laos' } }),
    prisma.country.upsert({ where: { code: 'MA' }, update: { nameKo: '모로코', nameEn: 'Morocco' }, create: { code: 'MA', nameKo: '모로코', nameEn: 'Morocco' } }),
    prisma.country.upsert({ where: { code: 'MM' }, update: { nameKo: '미얀마', nameEn: 'Myanmar' }, create: { code: 'MM', nameKo: '미얀마', nameEn: 'Myanmar' } }),
    prisma.country.upsert({ where: { code: 'MO' }, update: { nameKo: '마카오', nameEn: 'Macau' }, create: { code: 'MO', nameKo: '마카오', nameEn: 'Macau' } }),
    prisma.country.upsert({ where: { code: 'MX' }, update: { nameKo: '멕시코', nameEn: 'Mexico' }, create: { code: 'MX', nameKo: '멕시코', nameEn: 'Mexico' } }),
    prisma.country.upsert({ where: { code: 'MY' }, update: { nameKo: '말레이시아', nameEn: 'Malaysia' }, create: { code: 'MY', nameKo: '말레이시아', nameEn: 'Malaysia' } }),
    prisma.country.upsert({ where: { code: 'NL' }, update: { nameKo: '네덜란드', nameEn: 'Netherlands' }, create: { code: 'NL', nameKo: '네덜란드', nameEn: 'Netherlands' } }),
    prisma.country.upsert({ where: { code: 'NZ' }, update: { nameKo: '뉴질랜드', nameEn: 'New Zealand' }, create: { code: 'NZ', nameKo: '뉴질랜드', nameEn: 'New Zealand' } }),
    prisma.country.upsert({ where: { code: 'PE' }, update: { nameKo: '페루', nameEn: 'Peru' }, create: { code: 'PE', nameKo: '페루', nameEn: 'Peru' } }),
    prisma.country.upsert({ where: { code: 'PH' }, update: { nameKo: '필리핀', nameEn: 'Philippines' }, create: { code: 'PH', nameKo: '필리핀', nameEn: 'Philippines' } }),
    prisma.country.upsert({ where: { code: 'PL' }, update: { nameKo: '폴란드', nameEn: 'Poland' }, create: { code: 'PL', nameKo: '폴란드', nameEn: 'Poland' } }),
    prisma.country.upsert({ where: { code: 'PT' }, update: { nameKo: '포르투갈', nameEn: 'Portugal' }, create: { code: 'PT', nameKo: '포르투갈', nameEn: 'Portugal' } }),
    prisma.country.upsert({ where: { code: 'RU' }, update: { nameKo: '러시아', nameEn: 'Russia' }, create: { code: 'RU', nameKo: '러시아', nameEn: 'Russia' } }),
    prisma.country.upsert({ where: { code: 'SE' }, update: { nameKo: '스웨덴', nameEn: 'Sweden' }, create: { code: 'SE', nameKo: '스웨덴', nameEn: 'Sweden' } }),
    prisma.country.upsert({ where: { code: 'SG' }, update: { nameKo: '싱가포르', nameEn: 'Singapore' }, create: { code: 'SG', nameKo: '싱가포르', nameEn: 'Singapore' } }),
    prisma.country.upsert({ where: { code: 'TH' }, update: { nameKo: '태국', nameEn: 'Thailand' }, create: { code: 'TH', nameKo: '태국', nameEn: 'Thailand' } }),
    prisma.country.upsert({ where: { code: 'TR' }, update: { nameKo: '튀르키예', nameEn: 'Turkey' }, create: { code: 'TR', nameKo: '튀르키예', nameEn: 'Turkey' } }),
    prisma.country.upsert({ where: { code: 'TW' }, update: { nameKo: '대만', nameEn: 'Taiwan' }, create: { code: 'TW', nameKo: '대만', nameEn: 'Taiwan' } }),
    prisma.country.upsert({ where: { code: 'US' }, update: { nameKo: '미국', nameEn: 'United States' }, create: { code: 'US', nameKo: '미국', nameEn: 'United States' } }),
    prisma.country.upsert({ where: { code: 'VN' }, update: { nameKo: '베트남', nameEn: 'Vietnam' }, create: { code: 'VN', nameKo: '베트남', nameEn: 'Vietnam' } }),
    prisma.country.upsert({ where: { code: 'ZA' }, update: { nameKo: '남아프리카', nameEn: 'South Africa' }, create: { code: 'ZA', nameKo: '남아프리카', nameEn: 'South Africa' } }),
  ])
  console.log('✅ 국가 50개 완료')

  // ── 2. 국가 ID 맵 구성 ──────────────────────────────────────────
  const countryRows = await prisma.country.findMany({ select: { id: true, code: true } })
  const countryIdMap = Object.fromEntries(countryRows.map(c => [c.code, c.id]))

  // ── 3. 도시 삽입 (중복 nameKo+countryId 건너뜀) ─────────────────
  let inserted = 0, skipped = 0

  const cities: { nameKo: string; nameEn: string; iataCode: string | null; countryCode: string; isServed: boolean }[] = [
    { nameKo: '도쿄', nameEn: 'Tokyo', iataCode: 'TYO', countryCode: 'JP', isServed: true },
    { nameKo: '오사카', nameEn: 'Osaka', iataCode: 'OSA', countryCode: 'JP', isServed: true },
    { nameKo: '교토', nameEn: 'Kyoto', iataCode: null, countryCode: 'JP', isServed: true },
    { nameKo: '나고야', nameEn: 'Nagoya', iataCode: 'NGO', countryCode: 'JP', isServed: true },
    { nameKo: '삿포로', nameEn: 'Sapporo', iataCode: 'CTS', countryCode: 'JP', isServed: true },
    { nameKo: '후쿠오카', nameEn: 'Fukuoka', iataCode: 'FUK', countryCode: 'JP', isServed: true },
    { nameKo: '고베', nameEn: 'Kobe', iataCode: null, countryCode: 'JP', isServed: true },
    { nameKo: '히로시마', nameEn: 'Hiroshima', iataCode: 'HIJ', countryCode: 'JP', isServed: true },
    { nameKo: '센다이', nameEn: 'Sendai', iataCode: 'SDJ', countryCode: 'JP', isServed: true },
    { nameKo: '요코하마', nameEn: 'Yokohama', iataCode: null, countryCode: 'JP', isServed: true },
    { nameKo: '가와사키', nameEn: 'Kawasaki', iataCode: null, countryCode: 'JP', isServed: true },
    { nameKo: '기타큐슈', nameEn: 'Kitakyushu', iataCode: 'KKJ', countryCode: 'JP', isServed: true },
    { nameKo: '사이타마', nameEn: 'Saitama', iataCode: null, countryCode: 'JP', isServed: true },
    { nameKo: '지바', nameEn: 'Chiba', iataCode: null, countryCode: 'JP', isServed: true },
    { nameKo: '하마마쓰', nameEn: 'Hamamatsu', iataCode: null, countryCode: 'JP', isServed: true },
    { nameKo: '오카야마', nameEn: 'Okayama', iataCode: 'OKJ', countryCode: 'JP', isServed: true },
    { nameKo: '구마모토', nameEn: 'Kumamoto', iataCode: 'KMJ', countryCode: 'JP', isServed: true },
    { nameKo: '오키나와', nameEn: 'Okinawa', iataCode: 'OKA', countryCode: 'JP', isServed: true },
    { nameKo: '나라', nameEn: 'Nara', iataCode: null, countryCode: 'JP', isServed: true },
    { nameKo: '가나자와', nameEn: 'Kanazawa', iataCode: null, countryCode: 'JP', isServed: true },
    { nameKo: '방콕', nameEn: 'Bangkok', iataCode: 'BKK', countryCode: 'TH', isServed: true },
    { nameKo: '치앙마이', nameEn: 'Chiang Mai', iataCode: 'CNX', countryCode: 'TH', isServed: true },
    { nameKo: '파타야', nameEn: 'Pattaya', iataCode: null, countryCode: 'TH', isServed: true },
    { nameKo: '푸켓', nameEn: 'Phuket', iataCode: 'HKT', countryCode: 'TH', isServed: true },
    { nameKo: '후아힌', nameEn: 'Hua Hin', iataCode: null, countryCode: 'TH', isServed: true },
    { nameKo: '아유타야', nameEn: 'Ayutthaya', iataCode: null, countryCode: 'TH', isServed: true },
    { nameKo: '치앙라이', nameEn: 'Chiang Rai', iataCode: 'CEI', countryCode: 'TH', isServed: true },
    { nameKo: '코사무이', nameEn: 'Koh Samui', iataCode: 'USM', countryCode: 'TH', isServed: true },
    { nameKo: '코창', nameEn: 'Koh Chang', iataCode: null, countryCode: 'TH', isServed: true },
    { nameKo: '핫야이', nameEn: 'Hat Yai', iataCode: 'HDY', countryCode: 'TH', isServed: true },
    { nameKo: '나콘라차시마', nameEn: 'Nakhon Ratchasima', iataCode: null, countryCode: 'TH', isServed: true },
    { nameKo: '우돈타니', nameEn: '우돈타니', iataCode: null, countryCode: 'TH', isServed: true },
    { nameKo: '콘깬', nameEn: '콘깬', iataCode: null, countryCode: 'TH', isServed: true },
    { nameKo: '피마이', nameEn: '피마이', iataCode: null, countryCode: 'TH', isServed: true },
    { nameKo: '수코타이', nameEn: 'Sukhothai', iataCode: 'THS', countryCode: 'TH', isServed: true },
    { nameKo: '뉴욕', nameEn: 'New York', iataCode: 'NYC', countryCode: 'US', isServed: true },
    { nameKo: '로스앤젤레스', nameEn: 'Los Angeles', iataCode: 'LAX', countryCode: 'US', isServed: true },
    { nameKo: '시카고', nameEn: 'Chicago', iataCode: 'CHI', countryCode: 'US', isServed: true },
    { nameKo: '라스베가스', nameEn: '라스베가스', iataCode: null, countryCode: 'US', isServed: true },
    { nameKo: '호놀룰루', nameEn: '호놀룰루', iataCode: null, countryCode: 'US', isServed: true },
    { nameKo: '샌프란시스코', nameEn: 'San Francisco', iataCode: 'SFO', countryCode: 'US', isServed: true },
    { nameKo: '마이애미', nameEn: 'Miami', iataCode: 'MIA', countryCode: 'US', isServed: true },
    { nameKo: '워싱턴 D.C.', nameEn: '워싱턴 D.C.', iataCode: null, countryCode: 'US', isServed: true },
    { nameKo: '시애틀', nameEn: 'Seattle', iataCode: 'SEA', countryCode: 'US', isServed: true },
    { nameKo: '보스턴', nameEn: 'Boston', iataCode: 'BOS', countryCode: 'US', isServed: true },
    { nameKo: '올랜도', nameEn: 'Orlando', iataCode: 'MCO', countryCode: 'US', isServed: true },
    { nameKo: '덴버', nameEn: 'Denver', iataCode: 'DEN', countryCode: 'US', isServed: true },
    { nameKo: '포틀랜드', nameEn: 'Portland', iataCode: 'PDX', countryCode: 'US', isServed: true },
    { nameKo: '샌디에이고', nameEn: 'San Diego', iataCode: 'SAN', countryCode: 'US', isServed: true },
    { nameKo: '뉴올리언스', nameEn: 'New Orleans', iataCode: 'MSY', countryCode: 'US', isServed: true },
    { nameKo: '내슈빌', nameEn: 'Nashville', iataCode: 'BNA', countryCode: 'US', isServed: true },
    { nameKo: '피닉스', nameEn: 'Phoenix', iataCode: 'PHX', countryCode: 'US', isServed: true },
    { nameKo: '애틀란타', nameEn: '애틀란타', iataCode: null, countryCode: 'US', isServed: true },
    { nameKo: '달라스', nameEn: '달라스', iataCode: null, countryCode: 'US', isServed: true },
    { nameKo: '오스틴', nameEn: '오스틴', iataCode: null, countryCode: 'US', isServed: true },
    { nameKo: '하노이', nameEn: 'Hanoi', iataCode: 'HAN', countryCode: 'VN', isServed: true },
    { nameKo: '호치민', nameEn: 'Ho Chi Minh City', iataCode: 'SGN', countryCode: 'VN', isServed: true },
    { nameKo: '다낭', nameEn: 'Da Nang', iataCode: 'DAD', countryCode: 'VN', isServed: true },
    { nameKo: '호이안', nameEn: 'Hoi An', iataCode: null, countryCode: 'VN', isServed: true },
    { nameKo: '냐짱', nameEn: '냐짱', iataCode: null, countryCode: 'VN', isServed: true },
    { nameKo: '달랏', nameEn: 'Da Lat', iataCode: 'DLI', countryCode: 'VN', isServed: true },
    { nameKo: '후에', nameEn: 'Hue', iataCode: 'HUI', countryCode: 'VN', isServed: true },
    { nameKo: '하롱', nameEn: 'Ha Long', iataCode: null, countryCode: 'VN', isServed: true },
    { nameKo: '푸꾸옥', nameEn: 'Phu Quoc', iataCode: 'PQC', countryCode: 'VN', isServed: true },
    { nameKo: '사파', nameEn: 'Sa Pa', iataCode: null, countryCode: 'VN', isServed: true },
    { nameKo: '무이네', nameEn: 'Mui Ne', iataCode: null, countryCode: 'VN', isServed: true },
    { nameKo: '빈', nameEn: 'Vienna', iataCode: 'VIE', countryCode: 'VN', isServed: true },
    { nameKo: '하이퐁', nameEn: '하이퐁', iataCode: null, countryCode: 'VN', isServed: true },
    { nameKo: '칸호아', nameEn: 'Khanh Hoa', iataCode: null, countryCode: 'VN', isServed: true },
    { nameKo: '마닐라', nameEn: 'Manila', iataCode: 'MNL', countryCode: 'PH', isServed: true },
    { nameKo: '세부', nameEn: 'Cebu', iataCode: 'CEB', countryCode: 'PH', isServed: true },
    { nameKo: '보라카이', nameEn: 'Boracay', iataCode: 'MPH', countryCode: 'PH', isServed: true },
    { nameKo: '푸에르토프린세사', nameEn: '푸에르토프린세사', iataCode: null, countryCode: 'PH', isServed: true },
    { nameKo: '다바오', nameEn: 'Davao', iataCode: 'DVO', countryCode: 'PH', isServed: true },
    { nameKo: '바기오', nameEn: 'Baguio', iataCode: null, countryCode: 'PH', isServed: true },
    { nameKo: '시아르가오', nameEn: 'Siargao', iataCode: 'IAO', countryCode: 'PH', isServed: true },
    { nameKo: '일로일로', nameEn: 'Iloilo', iataCode: 'ILO', countryCode: 'PH', isServed: true },
    { nameKo: '코론', nameEn: '코론', iataCode: null, countryCode: 'PH', isServed: true },
    { nameKo: '앙헬레스', nameEn: '앙헬레스', iataCode: null, countryCode: 'PH', isServed: true },
    { nameKo: '베이징', nameEn: 'Beijing', iataCode: 'PEK', countryCode: 'CN', isServed: true },
    { nameKo: '상하이', nameEn: 'Shanghai', iataCode: 'SHA', countryCode: 'CN', isServed: true },
    { nameKo: '광저우', nameEn: 'Guangzhou', iataCode: 'CAN', countryCode: 'CN', isServed: true },
    { nameKo: '선전', nameEn: 'Shenzhen', iataCode: 'SZX', countryCode: 'CN', isServed: true },
    { nameKo: '청두', nameEn: 'Chengdu', iataCode: 'CTU', countryCode: 'CN', isServed: true },
    { nameKo: '항저우', nameEn: 'Hangzhou', iataCode: 'HGH', countryCode: 'CN', isServed: true },
    { nameKo: '시안', nameEn: 'Xi\'an', iataCode: 'XIY', countryCode: 'CN', isServed: true },
    { nameKo: '계림', nameEn: '계림', iataCode: null, countryCode: 'CN', isServed: true },
    { nameKo: '장가계', nameEn: 'Zhangjiajie', iataCode: 'DYG', countryCode: 'CN', isServed: true },
    { nameKo: '충칭', nameEn: 'Chongqing', iataCode: 'CKG', countryCode: 'CN', isServed: true },
    { nameKo: '쿤밍', nameEn: 'Kunming', iataCode: 'KMG', countryCode: 'CN', isServed: true },
    { nameKo: '리장', nameEn: 'Lijiang', iataCode: 'LJG', countryCode: 'CN', isServed: true },
    { nameKo: '하얼빈', nameEn: 'Harbin', iataCode: 'HRB', countryCode: 'CN', isServed: true },
    { nameKo: '난징', nameEn: 'Nanjing', iataCode: 'NKG', countryCode: 'CN', isServed: true },
    { nameKo: '우한', nameEn: 'Wuhan', iataCode: 'WUH', countryCode: 'CN', isServed: true },
    { nameKo: '시아먼', nameEn: '시아먼', iataCode: null, countryCode: 'CN', isServed: true },
    { nameKo: '칭다오', nameEn: 'Qingdao', iataCode: 'TAO', countryCode: 'CN', isServed: true },
    { nameKo: '하이난', nameEn: '하이난', iataCode: null, countryCode: 'CN', isServed: true },
    { nameKo: '싱가포르 도심', nameEn: '싱가포르 도심', iataCode: null, countryCode: 'SG', isServed: true },
    { nameKo: '마리나베이', nameEn: '마리나베이', iataCode: null, countryCode: 'SG', isServed: true },
    { nameKo: '센토사', nameEn: '센토사', iataCode: null, countryCode: 'SG', isServed: true },
    { nameKo: '주롱', nameEn: '주롱', iataCode: null, countryCode: 'SG', isServed: true },
    { nameKo: '창이', nameEn: '창이', iataCode: null, countryCode: 'SG', isServed: true },
    { nameKo: '오차드', nameEn: '오차드', iataCode: null, countryCode: 'SG', isServed: true },
    { nameKo: '발리', nameEn: 'Bali', iataCode: 'DPS', countryCode: 'ID', isServed: true },
    { nameKo: '자카르타', nameEn: 'Jakarta', iataCode: 'CGK', countryCode: 'ID', isServed: true },
    { nameKo: '수라바야', nameEn: 'Surabaya', iataCode: 'SUB', countryCode: 'ID', isServed: true },
    { nameKo: '욕야카르타', nameEn: '욕야카르타', iataCode: null, countryCode: 'ID', isServed: true },
    { nameKo: '롬복', nameEn: 'Lombok', iataCode: 'LOP', countryCode: 'ID', isServed: true },
    { nameKo: '코모도', nameEn: '코모도', iataCode: null, countryCode: 'ID', isServed: true },
    { nameKo: '라부안바조', nameEn: 'Labuan Bajo', iataCode: 'LBJ', countryCode: 'ID', isServed: true },
    { nameKo: '메단', nameEn: 'Medan', iataCode: 'KNO', countryCode: 'ID', isServed: true },
    { nameKo: '마나도', nameEn: 'Manado', iataCode: 'MDC', countryCode: 'ID', isServed: true },
    { nameKo: '마카사르', nameEn: 'Makassar', iataCode: 'UPG', countryCode: 'ID', isServed: true },
    { nameKo: '빈탄', nameEn: 'Bintan', iataCode: null, countryCode: 'ID', isServed: true },
    { nameKo: '바탐', nameEn: '바탐', iataCode: null, countryCode: 'ID', isServed: true },
    { nameKo: '홍콩 도심', nameEn: '홍콩 도심', iataCode: null, countryCode: 'HK', isServed: true },
    { nameKo: '침사추이', nameEn: 'Tsim Sha Tsui', iataCode: null, countryCode: 'HK', isServed: true },
    { nameKo: '몽콕', nameEn: 'Mong Kok', iataCode: null, countryCode: 'HK', isServed: true },
    { nameKo: '란콰이펑', nameEn: '란콰이펑', iataCode: null, countryCode: 'HK', isServed: true },
    { nameKo: '스탠리', nameEn: '스탠리', iataCode: null, countryCode: 'HK', isServed: true },
    { nameKo: '란타우', nameEn: 'Lantau', iataCode: null, countryCode: 'HK', isServed: true },
    { nameKo: '사이쿵', nameEn: '사이쿵', iataCode: null, countryCode: 'HK', isServed: true },
    { nameKo: '쿠알라룸푸르', nameEn: 'Kuala Lumpur', iataCode: 'KUL', countryCode: 'MY', isServed: true },
    { nameKo: '페낭', nameEn: 'Penang', iataCode: 'PEN', countryCode: 'MY', isServed: true },
    { nameKo: '코타키나발루', nameEn: 'Kota Kinabalu', iataCode: 'BKI', countryCode: 'MY', isServed: true },
    { nameKo: '코타바루', nameEn: 'Kota Bahru', iataCode: 'KBR', countryCode: 'MY', isServed: true },
    { nameKo: '랑카위', nameEn: 'Langkawi', iataCode: 'LGK', countryCode: 'MY', isServed: true },
    { nameKo: '말라카', nameEn: 'Malacca', iataCode: null, countryCode: 'MY', isServed: true },
    { nameKo: '조호르바루', nameEn: 'Johor Bahru', iataCode: 'JHB', countryCode: 'MY', isServed: true },
    { nameKo: '쿠칭', nameEn: 'Kuching', iataCode: 'KCH', countryCode: 'MY', isServed: true },
    { nameKo: '미리', nameEn: 'Miri', iataCode: 'MYY', countryCode: 'MY', isServed: true },
    { nameKo: '이포', nameEn: 'Ipoh', iataCode: null, countryCode: 'MY', isServed: true },
    { nameKo: '마카오 반도', nameEn: '마카오 반도', iataCode: null, countryCode: 'MO', isServed: true },
    { nameKo: '타이파', nameEn: 'Taipa', iataCode: null, countryCode: 'MO', isServed: true },
    { nameKo: '코타이', nameEn: 'Cotai', iataCode: null, countryCode: 'MO', isServed: true },
    { nameKo: '콜로안', nameEn: 'Coloane', iataCode: null, countryCode: 'MO', isServed: true },
    { nameKo: '런던', nameEn: 'London', iataCode: 'LON', countryCode: 'GB', isServed: true },
    { nameKo: '에든버러', nameEn: 'Edinburgh', iataCode: 'EDI', countryCode: 'GB', isServed: true },
    { nameKo: '맨체스터', nameEn: 'Manchester', iataCode: 'MAN', countryCode: 'GB', isServed: true },
    { nameKo: '옥스퍼드', nameEn: 'Oxford', iataCode: null, countryCode: 'GB', isServed: true },
    { nameKo: '캠브리지', nameEn: '캠브리지', iataCode: null, countryCode: 'GB', isServed: true },
    { nameKo: '리버풀', nameEn: 'Liverpool', iataCode: 'LPL', countryCode: 'GB', isServed: true },
    { nameKo: '버밍엄', nameEn: 'Birmingham', iataCode: 'BHX', countryCode: 'GB', isServed: true },
    { nameKo: '바스', nameEn: 'Bath', iataCode: null, countryCode: 'GB', isServed: true },
    { nameKo: '글래스고', nameEn: 'Glasgow', iataCode: 'GLA', countryCode: 'GB', isServed: true },
    { nameKo: '브라이턴', nameEn: 'Brighton', iataCode: null, countryCode: 'GB', isServed: true },
    { nameKo: '요크', nameEn: 'York', iataCode: null, countryCode: 'GB', isServed: true },
    { nameKo: '코츠월즈', nameEn: '코츠월즈', iataCode: null, countryCode: 'GB', isServed: true },
    { nameKo: '윈저', nameEn: '윈저', iataCode: null, countryCode: 'GB', isServed: true },
    { nameKo: '스트라트퍼드어폰에이번', nameEn: '스트라트퍼드어폰에이번', iataCode: null, countryCode: 'GB', isServed: true },
    { nameKo: '파리', nameEn: 'Paris', iataCode: 'PAR', countryCode: 'FR', isServed: true },
    { nameKo: '니스', nameEn: 'Nice', iataCode: 'NCE', countryCode: 'FR', isServed: true },
    { nameKo: '마르세유', nameEn: 'Marseille', iataCode: 'MRS', countryCode: 'FR', isServed: true },
    { nameKo: '리옹', nameEn: 'Lyon', iataCode: 'LYS', countryCode: 'FR', isServed: true },
    { nameKo: '보르도', nameEn: 'Bordeaux', iataCode: 'BOD', countryCode: 'FR', isServed: true },
    { nameKo: '스트라스부르', nameEn: 'Strasbourg', iataCode: 'SXB', countryCode: 'FR', isServed: true },
    { nameKo: '몽생미셸', nameEn: '몽생미셸', iataCode: null, countryCode: 'FR', isServed: true },
    { nameKo: '베르사유', nameEn: '베르사유', iataCode: null, countryCode: 'FR', isServed: true },
    { nameKo: '칸', nameEn: '칸', iataCode: null, countryCode: 'FR', isServed: true },
    { nameKo: '에즈', nameEn: '에즈', iataCode: null, countryCode: 'FR', isServed: true },
    { nameKo: '알비', nameEn: '알비', iataCode: null, countryCode: 'FR', isServed: true },
    { nameKo: '콜마르', nameEn: '콜마르', iataCode: null, countryCode: 'FR', isServed: true },
    { nameKo: '아비뇽', nameEn: 'Avignon', iataCode: null, countryCode: 'FR', isServed: true },
    { nameKo: '베를린', nameEn: 'Berlin', iataCode: 'BER', countryCode: 'DE', isServed: true },
    { nameKo: '뮌헨', nameEn: 'Munich', iataCode: 'MUC', countryCode: 'DE', isServed: true },
    { nameKo: '프랑크푸르트', nameEn: 'Frankfurt', iataCode: 'FRA', countryCode: 'DE', isServed: true },
    { nameKo: '함부르크', nameEn: 'Hamburg', iataCode: 'HAM', countryCode: 'DE', isServed: true },
    { nameKo: '쾰른', nameEn: 'Cologne', iataCode: 'CGN', countryCode: 'DE', isServed: true },
    { nameKo: '하이델베르크', nameEn: 'Heidelberg', iataCode: null, countryCode: 'DE', isServed: true },
    { nameKo: '로텐부르크', nameEn: '로텐부르크', iataCode: null, countryCode: 'DE', isServed: true },
    { nameKo: '드레스덴', nameEn: 'Dresden', iataCode: 'DRS', countryCode: 'DE', isServed: true },
    { nameKo: '뉘른베르크', nameEn: 'Nuremberg', iataCode: 'NUE', countryCode: 'DE', isServed: true },
    { nameKo: '슈투트가르트', nameEn: 'Stuttgart', iataCode: 'STR', countryCode: 'DE', isServed: true },
    { nameKo: '퓌센', nameEn: '퓌센', iataCode: null, countryCode: 'DE', isServed: true },
    { nameKo: '라이프치히', nameEn: 'Leipzig', iataCode: 'LEJ', countryCode: 'DE', isServed: true },
    { nameKo: '뤼베크', nameEn: '뤼베크', iataCode: null, countryCode: 'DE', isServed: true },
    { nameKo: '로마', nameEn: 'Rome', iataCode: 'ROM', countryCode: 'IT', isServed: true },
    { nameKo: '베네치아', nameEn: 'Venice', iataCode: 'VCE', countryCode: 'IT', isServed: true },
    { nameKo: '피렌체', nameEn: 'Florence', iataCode: 'FLR', countryCode: 'IT', isServed: true },
    { nameKo: '밀라노', nameEn: 'Milan', iataCode: 'MIL', countryCode: 'IT', isServed: true },
    { nameKo: '나폴리', nameEn: 'Naples', iataCode: 'NAP', countryCode: 'IT', isServed: true },
    { nameKo: '아말피', nameEn: 'Amalfi', iataCode: null, countryCode: 'IT', isServed: true },
    { nameKo: '친퀘테레', nameEn: 'Cinque Terre', iataCode: null, countryCode: 'IT', isServed: true },
    { nameKo: '팔레르모', nameEn: 'Palermo', iataCode: 'PMO', countryCode: 'IT', isServed: true },
    { nameKo: '볼로냐', nameEn: 'Bologna', iataCode: 'BLQ', countryCode: 'IT', isServed: true },
    { nameKo: '피사', nameEn: '피사', iataCode: null, countryCode: 'IT', isServed: true },
    { nameKo: '시에나', nameEn: '시에나', iataCode: null, countryCode: 'IT', isServed: true },
    { nameKo: '소렌토', nameEn: '소렌토', iataCode: null, countryCode: 'IT', isServed: true },
    { nameKo: '베로나', nameEn: 'Verona', iataCode: 'VRN', countryCode: 'IT', isServed: true },
    { nameKo: '토리노', nameEn: 'Turin', iataCode: 'TRN', countryCode: 'IT', isServed: true },
    { nameKo: '아씨시', nameEn: '아씨시', iataCode: null, countryCode: 'IT', isServed: true },
    { nameKo: '밴쿠버', nameEn: 'Vancouver', iataCode: 'YVR', countryCode: 'CA', isServed: true },
    { nameKo: '토론토', nameEn: 'Toronto', iataCode: 'YYZ', countryCode: 'CA', isServed: true },
    { nameKo: '퀘벡시티', nameEn: 'Quebec City', iataCode: 'YQB', countryCode: 'CA', isServed: true },
    { nameKo: '몬트리올', nameEn: 'Montreal', iataCode: 'YUL', countryCode: 'CA', isServed: true },
    { nameKo: '캘거리', nameEn: 'Calgary', iataCode: 'YYC', countryCode: 'CA', isServed: true },
    { nameKo: '재스퍼', nameEn: '재스퍼', iataCode: null, countryCode: 'CA', isServed: true },
    { nameKo: '밴프', nameEn: 'Banff', iataCode: null, countryCode: 'CA', isServed: true },
    { nameKo: '빅토리아', nameEn: 'Victoria', iataCode: 'YYJ', countryCode: 'CA', isServed: true },
    { nameKo: '오타와', nameEn: 'Ottawa', iataCode: 'YOW', countryCode: 'CA', isServed: true },
    { nameKo: '나이아가라폴스', nameEn: '나이아가라폴스', iataCode: null, countryCode: 'CA', isServed: true },
    { nameKo: '위슬러', nameEn: '위슬러', iataCode: null, countryCode: 'CA', isServed: true },
    { nameKo: '핼리팩스', nameEn: 'Halifax', iataCode: 'YHZ', countryCode: 'CA', isServed: true },
    { nameKo: '시드니', nameEn: 'Sydney', iataCode: 'SYD', countryCode: 'AU', isServed: true },
    { nameKo: '멜버른', nameEn: 'Melbourne', iataCode: 'MEL', countryCode: 'AU', isServed: true },
    { nameKo: '브리즈번', nameEn: 'Brisbane', iataCode: 'BNE', countryCode: 'AU', isServed: true },
    { nameKo: '케언스', nameEn: 'Cairns', iataCode: 'CNS', countryCode: 'AU', isServed: true },
    { nameKo: '퍼스', nameEn: 'Perth', iataCode: 'PER', countryCode: 'AU', isServed: true },
    { nameKo: '골드코스트', nameEn: 'Gold Coast', iataCode: 'OOL', countryCode: 'AU', isServed: true },
    { nameKo: '애들레이드', nameEn: 'Adelaide', iataCode: 'ADL', countryCode: 'AU', isServed: true },
    { nameKo: '다윈', nameEn: 'Darwin', iataCode: 'DRW', countryCode: 'AU', isServed: true },
    { nameKo: '울룰루', nameEn: '울룰루', iataCode: null, countryCode: 'AU', isServed: true },
    { nameKo: '포트더글러스', nameEn: '포트더글러스', iataCode: null, countryCode: 'AU', isServed: true },
    { nameKo: '호바트', nameEn: 'Hobart', iataCode: 'HBA', countryCode: 'AU', isServed: true },
    { nameKo: '타이베이', nameEn: 'Taipei', iataCode: 'TPE', countryCode: 'TW', isServed: true },
    { nameKo: '타이중', nameEn: 'Taichung', iataCode: 'RMQ', countryCode: 'TW', isServed: true },
    { nameKo: '타이난', nameEn: 'Tainan', iataCode: 'TNN', countryCode: 'TW', isServed: true },
    { nameKo: '가오슝', nameEn: 'Kaohsiung', iataCode: 'KHH', countryCode: 'TW', isServed: true },
    { nameKo: '화롄', nameEn: 'Hualien', iataCode: 'HUN', countryCode: 'TW', isServed: true },
    { nameKo: '타이동', nameEn: 'Taitung', iataCode: 'TTT', countryCode: 'TW', isServed: true },
    { nameKo: '일월담', nameEn: '일월담', iataCode: null, countryCode: 'TW', isServed: true },
    { nameKo: '아리산', nameEn: '아리산', iataCode: null, countryCode: 'TW', isServed: true },
    { nameKo: '지우펀', nameEn: '지우펀', iataCode: null, countryCode: 'TW', isServed: true },
    { nameKo: '기룽', nameEn: '기룽', iataCode: null, countryCode: 'TW', isServed: true },
    { nameKo: '마드리드', nameEn: 'Madrid', iataCode: 'MAD', countryCode: 'ES', isServed: true },
    { nameKo: '바르셀로나', nameEn: 'Barcelona', iataCode: 'BCN', countryCode: 'ES', isServed: true },
    { nameKo: '세비야', nameEn: 'Seville', iataCode: 'SVQ', countryCode: 'ES', isServed: true },
    { nameKo: '그라나다', nameEn: 'Granada', iataCode: 'GRX', countryCode: 'ES', isServed: true },
    { nameKo: '톨레도', nameEn: 'Toledo', iataCode: null, countryCode: 'ES', isServed: true },
    { nameKo: '발렌시아', nameEn: 'Valencia', iataCode: 'VLC', countryCode: 'ES', isServed: true },
    { nameKo: '빌바오', nameEn: 'Bilbao', iataCode: 'BIO', countryCode: 'ES', isServed: true },
    { nameKo: '산세바스티안', nameEn: '산세바스티안', iataCode: null, countryCode: 'ES', isServed: true },
    { nameKo: '말라가', nameEn: 'Malaga', iataCode: 'AGP', countryCode: 'ES', isServed: true },
    { nameKo: '코르도바', nameEn: 'Cordoba', iataCode: null, countryCode: 'ES', isServed: true },
    { nameKo: '팜플로나', nameEn: '팜플로나', iataCode: null, countryCode: 'ES', isServed: true },
    { nameKo: '살라망카', nameEn: '살라망카', iataCode: null, countryCode: 'ES', isServed: true },
    { nameKo: '산티아고데콤포스텔라', nameEn: 'Santiago de Compostela', iataCode: 'SCQ', countryCode: 'ES', isServed: true },
    { nameKo: '양곤', nameEn: 'Yangon', iataCode: 'RGN', countryCode: 'MM', isServed: true },
    { nameKo: '만달레이', nameEn: 'Mandalay', iataCode: 'MDL', countryCode: 'MM', isServed: true },
    { nameKo: '바간', nameEn: 'Bagan', iataCode: 'NYU', countryCode: 'MM', isServed: true },
    { nameKo: '인레호수', nameEn: '인레호수', iataCode: null, countryCode: 'MM', isServed: true },
    { nameKo: '응아팔리', nameEn: '응아팔리', iataCode: null, countryCode: 'MM', isServed: true },
    { nameKo: '민군', nameEn: '민군', iataCode: null, countryCode: 'MM', isServed: true },
    { nameKo: '포파산', nameEn: '포파산', iataCode: null, countryCode: 'MM', isServed: true },
    { nameKo: '오클랜드', nameEn: 'Auckland', iataCode: 'AKL', countryCode: 'NZ', isServed: true },
    { nameKo: '퀸스타운', nameEn: 'Queenstown', iataCode: 'ZQN', countryCode: 'NZ', isServed: true },
    { nameKo: '크라이스트처치', nameEn: 'Christchurch', iataCode: 'CHC', countryCode: 'NZ', isServed: true },
    { nameKo: '웰링턴', nameEn: 'Wellington', iataCode: 'WLG', countryCode: 'NZ', isServed: true },
    { nameKo: '로토루아', nameEn: 'Rotorua', iataCode: 'ROT', countryCode: 'NZ', isServed: true },
    { nameKo: '밀포드사운드', nameEn: '밀포드사운드', iataCode: null, countryCode: 'NZ', isServed: true },
    { nameKo: '와나카', nameEn: '와나카', iataCode: null, countryCode: 'NZ', isServed: true },
    { nameKo: '테카포', nameEn: '테카포', iataCode: null, countryCode: 'NZ', isServed: true },
    { nameKo: '넬슨', nameEn: 'Nelson', iataCode: 'NSN', countryCode: 'NZ', isServed: true },
    { nameKo: '더니든', nameEn: 'Dunedin', iataCode: 'DUD', countryCode: 'NZ', isServed: true },
    { nameKo: '취리히', nameEn: 'Zurich', iataCode: 'ZRH', countryCode: 'CH', isServed: true },
    { nameKo: '제네바', nameEn: 'Geneva', iataCode: 'GVA', countryCode: 'CH', isServed: true },
    { nameKo: '인터라켄', nameEn: 'Interlaken', iataCode: null, countryCode: 'CH', isServed: true },
    { nameKo: '루체른', nameEn: 'Lucerne', iataCode: null, countryCode: 'CH', isServed: true },
    { nameKo: '베른', nameEn: 'Bern', iataCode: 'BRN', countryCode: 'CH', isServed: true },
    { nameKo: '체르마트', nameEn: 'Zermatt', iataCode: null, countryCode: 'CH', isServed: true },
    { nameKo: '생모리츠', nameEn: '생모리츠', iataCode: null, countryCode: 'CH', isServed: true },
    { nameKo: '로잔', nameEn: 'Lausanne', iataCode: null, countryCode: 'CH', isServed: true },
    { nameKo: '루가노', nameEn: 'Lugano', iataCode: 'LUG', countryCode: 'CH', isServed: true },
    { nameKo: '그린델발트', nameEn: '그린델발트', iataCode: null, countryCode: 'CH', isServed: true },
    { nameKo: '융프라우', nameEn: '융프라우', iataCode: null, countryCode: 'CH', isServed: true },
    { nameKo: '암스테르담', nameEn: 'Amsterdam', iataCode: 'AMS', countryCode: 'NL', isServed: true },
    { nameKo: '잔담', nameEn: '잔담', iataCode: null, countryCode: 'NL', isServed: true },
    { nameKo: '헤이그', nameEn: 'The Hague', iataCode: null, countryCode: 'NL', isServed: true },
    { nameKo: '로테르담', nameEn: 'Rotterdam', iataCode: 'RTM', countryCode: 'NL', isServed: true },
    { nameKo: '위트레흐트', nameEn: 'Utrecht', iataCode: null, countryCode: 'NL', isServed: true },
    { nameKo: '마스트리흐트', nameEn: '마스트리흐트', iataCode: null, countryCode: 'NL', isServed: true },
    { nameKo: '흐로닝언', nameEn: '흐로닝언', iataCode: null, countryCode: 'NL', isServed: true },
    { nameKo: '델프트', nameEn: '델프트', iataCode: null, countryCode: 'NL', isServed: true },
    { nameKo: '하를렘', nameEn: '하를렘', iataCode: null, countryCode: 'NL', isServed: true },
    { nameKo: '킨더다이크', nameEn: '킨더다이크', iataCode: null, countryCode: 'NL', isServed: true },
    { nameKo: '리스본', nameEn: 'Lisbon', iataCode: 'LIS', countryCode: 'PT', isServed: true },
    { nameKo: '포르투', nameEn: 'Porto', iataCode: 'OPO', countryCode: 'PT', isServed: true },
    { nameKo: '신트라', nameEn: 'Sintra', iataCode: null, countryCode: 'PT', isServed: true },
    { nameKo: '알가르브', nameEn: '알가르브', iataCode: null, countryCode: 'PT', isServed: true },
    { nameKo: '오비두스', nameEn: '오비두스', iataCode: null, countryCode: 'PT', isServed: true },
    { nameKo: '에보라', nameEn: 'Evora', iataCode: null, countryCode: 'PT', isServed: true },
    { nameKo: '코임브라', nameEn: 'Coimbra', iataCode: null, countryCode: 'PT', isServed: true },
    { nameKo: '브라가', nameEn: 'Braga', iataCode: null, countryCode: 'PT', isServed: true },
    { nameKo: '아제이다스', nameEn: '아제이다스', iataCode: null, countryCode: 'PT', isServed: true },
    { nameKo: '아테네', nameEn: 'Athens', iataCode: 'ATH', countryCode: 'GR', isServed: true },
    { nameKo: '산토리니', nameEn: 'Santorini', iataCode: 'JTR', countryCode: 'GR', isServed: true },
    { nameKo: '미코노스', nameEn: 'Mykonos', iataCode: 'JMK', countryCode: 'GR', isServed: true },
    { nameKo: '헤라클리온', nameEn: '헤라클리온', iataCode: null, countryCode: 'GR', isServed: true },
    { nameKo: '로도스', nameEn: 'Rhodes', iataCode: 'RHO', countryCode: 'GR', isServed: true },
    { nameKo: '코르푸', nameEn: 'Corfu', iataCode: 'CFU', countryCode: 'GR', isServed: true },
    { nameKo: '테살로니키', nameEn: 'Thessaloniki', iataCode: 'SKG', countryCode: 'GR', isServed: true },
    { nameKo: '델포이', nameEn: '델포이', iataCode: null, countryCode: 'GR', isServed: true },
    { nameKo: '올림피아', nameEn: '올림피아', iataCode: null, countryCode: 'GR', isServed: true },
    { nameKo: '메테오라', nameEn: '메테오라', iataCode: null, countryCode: 'GR', isServed: true },
    { nameKo: '파트모스', nameEn: '파트모스', iataCode: null, countryCode: 'GR', isServed: true },
    { nameKo: '멕시코시티', nameEn: 'Mexico City', iataCode: 'MEX', countryCode: 'MX', isServed: true },
    { nameKo: '칸쿤', nameEn: 'Cancun', iataCode: 'CUN', countryCode: 'MX', isServed: true },
    { nameKo: '툴룸', nameEn: 'Tulum', iataCode: null, countryCode: 'MX', isServed: true },
    { nameKo: '플라야델카르멘', nameEn: 'Playa del Carmen', iataCode: null, countryCode: 'MX', isServed: true },
    { nameKo: '과달라하라', nameEn: 'Guadalajara', iataCode: 'GDL', countryCode: 'MX', isServed: true },
    { nameKo: '오악사카', nameEn: 'Oaxaca', iataCode: 'OAX', countryCode: 'MX', isServed: true },
    { nameKo: '산크리스토발', nameEn: 'San Cristobal', iataCode: null, countryCode: 'MX', isServed: true },
    { nameKo: '과나후아토', nameEn: 'Guanajuato', iataCode: 'BJX', countryCode: 'MX', isServed: true },
    { nameKo: '케레타로', nameEn: '케레타로', iataCode: null, countryCode: 'MX', isServed: true },
    { nameKo: '푸에블라', nameEn: '푸에블라', iataCode: null, countryCode: 'MX', isServed: true },
    { nameKo: '메리다', nameEn: 'Merida', iataCode: 'MID', countryCode: 'MX', isServed: true },
    { nameKo: '빈', nameEn: 'Vienna', iataCode: 'VIE', countryCode: 'AT', isServed: true },
    { nameKo: '잘츠부르크', nameEn: 'Salzburg', iataCode: 'SZG', countryCode: 'AT', isServed: true },
    { nameKo: '인스브루크', nameEn: 'Innsbruck', iataCode: 'INN', countryCode: 'AT', isServed: true },
    { nameKo: '그라츠', nameEn: 'Graz', iataCode: 'GRZ', countryCode: 'AT', isServed: true },
    { nameKo: '할슈타트', nameEn: '할슈타트', iataCode: null, countryCode: 'AT', isServed: true },
    { nameKo: '린츠', nameEn: 'Linz', iataCode: 'LNZ', countryCode: 'AT', isServed: true },
    { nameKo: '크렘스', nameEn: '크렘스', iataCode: null, countryCode: 'AT', isServed: true },
    { nameKo: '장크트볼프강', nameEn: '장크트볼프강', iataCode: null, countryCode: 'AT', isServed: true },
    { nameKo: '이스탄불', nameEn: 'Istanbul', iataCode: 'IST', countryCode: 'TR', isServed: true },
    { nameKo: '카파도키아', nameEn: 'Cappadocia', iataCode: 'NAV', countryCode: 'TR', isServed: true },
    { nameKo: '파묵칼레', nameEn: 'Pamukkale', iataCode: null, countryCode: 'TR', isServed: true },
    { nameKo: '에페소스', nameEn: '에페소스', iataCode: null, countryCode: 'TR', isServed: true },
    { nameKo: '안탈리아', nameEn: 'Antalya', iataCode: 'AYT', countryCode: 'TR', isServed: true },
    { nameKo: '트라브존', nameEn: 'Trabzon', iataCode: 'TZX', countryCode: 'TR', isServed: true },
    { nameKo: '보드룸', nameEn: 'Bodrum', iataCode: 'BJV', countryCode: 'TR', isServed: true },
    { nameKo: '이즈미르', nameEn: 'Izmir', iataCode: 'ADB', countryCode: 'TR', isServed: true },
    { nameKo: '앙카라', nameEn: 'Ankara', iataCode: 'ANK', countryCode: 'TR', isServed: true },
    { nameKo: '우르파', nameEn: '우르파', iataCode: null, countryCode: 'TR', isServed: true },
    { nameKo: '프라하', nameEn: 'Prague', iataCode: 'PRG', countryCode: 'CZ', isServed: true },
    { nameKo: '체스키크룸로프', nameEn: 'Cesky Krumlov', iataCode: null, countryCode: 'CZ', isServed: true },
    { nameKo: '브르노', nameEn: 'Brno', iataCode: 'BRQ', countryCode: 'CZ', isServed: true },
    { nameKo: '카를로비바리', nameEn: 'Karlovy Vary', iataCode: 'KLV', countryCode: 'CZ', isServed: true },
    { nameKo: '오슈트라바', nameEn: '오슈트라바', iataCode: null, countryCode: 'CZ', isServed: true },
    { nameKo: '플젠', nameEn: '플젠', iataCode: null, countryCode: 'CZ', isServed: true },
    { nameKo: '텔치', nameEn: '텔치', iataCode: null, countryCode: 'CZ', isServed: true },
    { nameKo: '부다페스트', nameEn: 'Budapest', iataCode: 'BUD', countryCode: 'HU', isServed: true },
    { nameKo: '에게르', nameEn: 'Eger', iataCode: null, countryCode: 'HU', isServed: true },
    { nameKo: '페치', nameEn: 'Pecs', iataCode: null, countryCode: 'HU', isServed: true },
    { nameKo: '죄르', nameEn: 'Gyor', iataCode: null, countryCode: 'HU', isServed: true },
    { nameKo: '데브레첸', nameEn: 'Debrecen', iataCode: 'DEB', countryCode: 'HU', isServed: true },
    { nameKo: '비셰그라드', nameEn: '비셰그라드', iataCode: null, countryCode: 'HU', isServed: true },
    { nameKo: '호르토바지', nameEn: '호르토바지', iataCode: null, countryCode: 'HU', isServed: true },
    { nameKo: '모스크바', nameEn: 'Moscow', iataCode: 'MOW', countryCode: 'RU', isServed: true },
    { nameKo: '상트페테르부르크', nameEn: 'Saint Petersburg', iataCode: 'LED', countryCode: 'RU', isServed: true },
    { nameKo: '블라디보스토크', nameEn: 'Vladivostok', iataCode: 'VVO', countryCode: 'RU', isServed: true },
    { nameKo: '소치', nameEn: '소치', iataCode: null, countryCode: 'RU', isServed: true },
    { nameKo: '예카테린부르크', nameEn: 'Yekaterinburg', iataCode: 'SVX', countryCode: 'RU', isServed: true },
    { nameKo: '카잔', nameEn: 'Kazan', iataCode: 'KZN', countryCode: 'RU', isServed: true },
    { nameKo: '이르쿠츠크', nameEn: 'Irkutsk', iataCode: 'IKT', countryCode: 'RU', isServed: true },
    { nameKo: '씨엠립', nameEn: 'Siem Reap', iataCode: 'REP', countryCode: 'KH', isServed: true },
    { nameKo: '프놈펜', nameEn: 'Phnom Penh', iataCode: 'PNH', countryCode: 'KH', isServed: true },
    { nameKo: '시아누크빌', nameEn: '시아누크빌', iataCode: null, countryCode: 'KH', isServed: true },
    { nameKo: '캄폿', nameEn: 'Kampot', iataCode: null, countryCode: 'KH', isServed: true },
    { nameKo: '케프', nameEn: 'Kep', iataCode: null, countryCode: 'KH', isServed: true },
    { nameKo: '바탐방', nameEn: 'Battambang', iataCode: 'BBM', countryCode: 'KH', isServed: true },
    { nameKo: '뉴델리', nameEn: '뉴델리', iataCode: null, countryCode: 'IN', isServed: true },
    { nameKo: '뭄바이', nameEn: 'Mumbai', iataCode: 'BOM', countryCode: 'IN', isServed: true },
    { nameKo: '아그라', nameEn: 'Agra', iataCode: 'AGR', countryCode: 'IN', isServed: true },
    { nameKo: '자이푸르', nameEn: 'Jaipur', iataCode: 'JAI', countryCode: 'IN', isServed: true },
    { nameKo: '바라나시', nameEn: '바라나시', iataCode: null, countryCode: 'IN', isServed: true },
    { nameKo: '첸나이', nameEn: 'Chennai', iataCode: 'MAA', countryCode: 'IN', isServed: true },
    { nameKo: '고아', nameEn: 'Goa', iataCode: 'GOI', countryCode: 'IN', isServed: true },
    { nameKo: '콜카타', nameEn: 'Kolkata', iataCode: 'CCU', countryCode: 'IN', isServed: true },
    { nameKo: '뱅갈로르', nameEn: '뱅갈로르', iataCode: null, countryCode: 'IN', isServed: true },
    { nameKo: '코치', nameEn: '코치', iataCode: null, countryCode: 'IN', isServed: true },
    { nameKo: '우다이푸르', nameEn: '우다이푸르', iataCode: null, countryCode: 'IN', isServed: true },
    { nameKo: '다람살라', nameEn: '다람살라', iataCode: null, countryCode: 'IN', isServed: true },
    { nameKo: '강톡', nameEn: '강톡', iataCode: null, countryCode: 'IN', isServed: true },
    { nameKo: '마이소르', nameEn: '마이소르', iataCode: null, countryCode: 'IN', isServed: true },
    { nameKo: '레이캬비크', nameEn: 'Reykjavik', iataCode: 'RKV', countryCode: 'IS', isServed: true },
    { nameKo: '아퀴레이리', nameEn: '아퀴레이리', iataCode: null, countryCode: 'IS', isServed: true },
    { nameKo: '미바튼', nameEn: '미바튼', iataCode: null, countryCode: 'IS', isServed: true },
    { nameKo: '스카프타펠', nameEn: 'Skaftafell', iataCode: null, countryCode: 'IS', isServed: true },
    { nameKo: '블루라군', nameEn: '블루라군', iataCode: null, countryCode: 'IS', isServed: true },
    { nameKo: '셀포스', nameEn: 'Selfoss', iataCode: null, countryCode: 'IS', isServed: true },
    { nameKo: '스나이펠스요쿨', nameEn: '스나이펠스요쿨', iataCode: null, countryCode: 'IS', isServed: true },
    { nameKo: '비크', nameEn: 'Vik', iataCode: null, countryCode: 'IS', isServed: true },
    { nameKo: '두브로브니크', nameEn: 'Dubrovnik', iataCode: 'DBV', countryCode: 'HR', isServed: true },
    { nameKo: '스플리트', nameEn: 'Split', iataCode: 'SPU', countryCode: 'HR', isServed: true },
    { nameKo: '플리트비체', nameEn: '플리트비체', iataCode: null, countryCode: 'HR', isServed: true },
    { nameKo: '자그레브', nameEn: 'Zagreb', iataCode: 'ZAG', countryCode: 'HR', isServed: true },
    { nameKo: '흐바르', nameEn: 'Hvar', iataCode: null, countryCode: 'HR', isServed: true },
    { nameKo: '코르출라', nameEn: '코르출라', iataCode: null, countryCode: 'HR', isServed: true },
    { nameKo: '로비니', nameEn: '로비니', iataCode: null, countryCode: 'HR', isServed: true },
    { nameKo: '자다르', nameEn: 'Zadar', iataCode: 'ZAD', countryCode: 'HR', isServed: true },
    { nameKo: '스톡홀름', nameEn: 'Stockholm', iataCode: 'STO', countryCode: 'SE', isServed: true },
    { nameKo: '예테보리', nameEn: 'Gothenburg', iataCode: 'GOT', countryCode: 'SE', isServed: true },
    { nameKo: '말뫼', nameEn: 'Malmo', iataCode: 'MMX', countryCode: 'SE', isServed: true },
    { nameKo: '아비스코', nameEn: '아비스코', iataCode: null, countryCode: 'SE', isServed: true },
    { nameKo: '달라나', nameEn: '달라나', iataCode: null, countryCode: 'SE', isServed: true },
    { nameKo: '웁살라', nameEn: 'Uppsala', iataCode: null, countryCode: 'SE', isServed: true },
    { nameKo: '빌링에', nameEn: '빌링에', iataCode: null, countryCode: 'SE', isServed: true },
    { nameKo: '고틀란드', nameEn: '고틀란드', iataCode: null, countryCode: 'SE', isServed: true },
    { nameKo: '브뤼셀', nameEn: 'Brussels', iataCode: 'BRU', countryCode: 'BE', isServed: true },
    { nameKo: '브뤼헤', nameEn: 'Bruges', iataCode: null, countryCode: 'BE', isServed: true },
    { nameKo: '겐트', nameEn: 'Ghent', iataCode: null, countryCode: 'BE', isServed: true },
    { nameKo: '앤트워프', nameEn: 'Antwerp', iataCode: 'ANR', countryCode: 'BE', isServed: true },
    { nameKo: '리에주', nameEn: 'Liege', iataCode: 'LGG', countryCode: 'BE', isServed: true },
    { nameKo: '나뮈르', nameEn: 'Namur', iataCode: null, countryCode: 'BE', isServed: true },
    { nameKo: '딘낭', nameEn: '딘낭', iataCode: null, countryCode: 'BE', isServed: true },
    { nameKo: '리우데자네이루', nameEn: 'Rio de Janeiro', iataCode: 'RIO', countryCode: 'BR', isServed: true },
    { nameKo: '상파울루', nameEn: 'Sao Paulo', iataCode: 'SAO', countryCode: 'BR', isServed: true },
    { nameKo: '이과수폭포', nameEn: '이과수폭포', iataCode: null, countryCode: 'BR', isServed: true },
    { nameKo: '살바도르', nameEn: 'Salvador', iataCode: 'SSA', countryCode: 'BR', isServed: true },
    { nameKo: '포르탈레자', nameEn: 'Fortaleza', iataCode: 'FOR', countryCode: 'BR', isServed: true },
    { nameKo: '마나우스', nameEn: 'Manaus', iataCode: 'MAO', countryCode: 'BR', isServed: true },
    { nameKo: '브라질리아', nameEn: 'Brasilia', iataCode: 'BSB', countryCode: 'BR', isServed: true },
    { nameKo: '플로리아노폴리스', nameEn: '플로리아노폴리스', iataCode: null, countryCode: 'BR', isServed: true },
    { nameKo: '바르샤바', nameEn: 'Warsaw', iataCode: 'WAW', countryCode: 'PL', isServed: true },
    { nameKo: '크라쿠프', nameEn: 'Krakow', iataCode: 'KRK', countryCode: 'PL', isServed: true },
    { nameKo: '브로츠와프', nameEn: 'Wroclaw', iataCode: 'WRO', countryCode: 'PL', isServed: true },
    { nameKo: '그단스크', nameEn: 'Gdansk', iataCode: 'GDN', countryCode: 'PL', isServed: true },
    { nameKo: '자코파네', nameEn: '자코파네', iataCode: null, countryCode: 'PL', isServed: true },
    { nameKo: '아우슈비츠', nameEn: '아우슈비츠', iataCode: null, countryCode: 'PL', isServed: true },
    { nameKo: '포즈난', nameEn: 'Poznan', iataCode: 'POZ', countryCode: 'PL', isServed: true },
    { nameKo: '토룬', nameEn: '토룬', iataCode: null, countryCode: 'PL', isServed: true },
    { nameKo: '암만', nameEn: 'Amman', iataCode: 'AMM', countryCode: 'JO', isServed: true },
    { nameKo: '페트라', nameEn: 'Petra', iataCode: null, countryCode: 'JO', isServed: true },
    { nameKo: '와디럼', nameEn: 'Wadi Rum', iataCode: null, countryCode: 'JO', isServed: true },
    { nameKo: '아카바', nameEn: 'Aqaba', iataCode: 'AQJ', countryCode: 'JO', isServed: true },
    { nameKo: '제라쉬', nameEn: '제라쉬', iataCode: null, countryCode: 'JO', isServed: true },
    { nameKo: '마다바', nameEn: 'Madaba', iataCode: null, countryCode: 'JO', isServed: true },
    { nameKo: '케락', nameEn: '케락', iataCode: null, countryCode: 'JO', isServed: true },
    { nameKo: '카이로', nameEn: 'Cairo', iataCode: 'CAI', countryCode: 'EG', isServed: true },
    { nameKo: '룩소르', nameEn: 'Luxor', iataCode: 'LXR', countryCode: 'EG', isServed: true },
    { nameKo: '아스완', nameEn: 'Aswan', iataCode: 'ASW', countryCode: 'EG', isServed: true },
    { nameKo: '후르가다', nameEn: 'Hurghada', iataCode: 'HRG', countryCode: 'EG', isServed: true },
    { nameKo: '샤름엘셰이크', nameEn: 'Sharm el-Sheikh', iataCode: 'SSH', countryCode: 'EG', isServed: true },
    { nameKo: '알렉산드리아', nameEn: 'Alexandria', iataCode: 'ALY', countryCode: 'EG', isServed: true },
    { nameKo: '다합', nameEn: '다합', iataCode: null, countryCode: 'EG', isServed: true },
    { nameKo: '알마티', nameEn: 'Almaty', iataCode: 'ALA', countryCode: 'KZ', isServed: true },
    { nameKo: '아스타나', nameEn: '아스타나', iataCode: null, countryCode: 'KZ', isServed: true },
    { nameKo: '시므켄트', nameEn: '시므켄트', iataCode: null, countryCode: 'KZ', isServed: true },
    { nameKo: '악토베', nameEn: 'Aktobe', iataCode: 'AKX', countryCode: 'KZ', isServed: true },
    { nameKo: '세메이', nameEn: '세메이', iataCode: null, countryCode: 'KZ', isServed: true },
    { nameKo: '루앙프라방', nameEn: 'Luang Prabang', iataCode: 'LPQ', countryCode: 'LA', isServed: true },
    { nameKo: '비엔티안', nameEn: 'Vientiane', iataCode: 'VTE', countryCode: 'LA', isServed: true },
    { nameKo: '방비엥', nameEn: 'Vang Vieng', iataCode: null, countryCode: 'LA', isServed: true },
    { nameKo: '팍세', nameEn: 'Pakse', iataCode: 'PKZ', countryCode: 'LA', isServed: true },
    { nameKo: '씨판돈', nameEn: 'Si Phan Don', iataCode: null, countryCode: 'LA', isServed: true },
    { nameKo: '두바이', nameEn: 'Dubai', iataCode: 'DXB', countryCode: 'AE', isServed: true },
    { nameKo: '아부다비', nameEn: 'Abu Dhabi', iataCode: 'AUH', countryCode: 'AE', isServed: true },
    { nameKo: '샤르자', nameEn: 'Sharjah', iataCode: 'SHJ', countryCode: 'AE', isServed: true },
    { nameKo: '라스알카이마', nameEn: 'Ras Al Khaimah', iataCode: 'RKT', countryCode: 'AE', isServed: true },
    { nameKo: '아지만', nameEn: '아지만', iataCode: null, countryCode: 'AE', isServed: true },
    { nameKo: '후자이라', nameEn: 'Fujairah', iataCode: 'FJR', countryCode: 'AE', isServed: true },
    { nameKo: '케이프타운', nameEn: 'Cape Town', iataCode: 'CPT', countryCode: 'ZA', isServed: true },
    { nameKo: '요하네스버그', nameEn: 'Johannesburg', iataCode: 'JNB', countryCode: 'ZA', isServed: true },
    { nameKo: '크루거국립공원', nameEn: '크루거국립공원', iataCode: null, countryCode: 'ZA', isServed: true },
    { nameKo: '더반', nameEn: 'Durban', iataCode: 'DUR', countryCode: 'ZA', isServed: true },
    { nameKo: '포트엘리자베스', nameEn: 'Port Elizabeth', iataCode: 'PLZ', countryCode: 'ZA', isServed: true },
    { nameKo: '가든루트', nameEn: '가든루트', iataCode: null, countryCode: 'ZA', isServed: true },
    { nameKo: '스텔렌보스', nameEn: '스텔렌보스', iataCode: null, countryCode: 'ZA', isServed: true },
    { nameKo: '쿠스코', nameEn: 'Cusco', iataCode: 'CUZ', countryCode: 'PE', isServed: true },
    { nameKo: '마추픽추', nameEn: '마추픽추', iataCode: null, countryCode: 'PE', isServed: true },
    { nameKo: '리마', nameEn: 'Lima', iataCode: 'LIM', countryCode: 'PE', isServed: true },
    { nameKo: '아레키파', nameEn: 'Arequipa', iataCode: 'AQP', countryCode: 'PE', isServed: true },
    { nameKo: '푸노', nameEn: 'Puno', iataCode: null, countryCode: 'PE', isServed: true },
    { nameKo: '이키토스', nameEn: 'Iquitos', iataCode: 'IQT', countryCode: 'PE', isServed: true },
    { nameKo: '우아라스', nameEn: '우아라스', iataCode: null, countryCode: 'PE', isServed: true },
    { nameKo: '나스카', nameEn: 'Nasca', iataCode: null, countryCode: 'PE', isServed: true },
    { nameKo: '마라케시', nameEn: 'Marrakech', iataCode: 'RAK', countryCode: 'MA', isServed: true },
    { nameKo: '페스', nameEn: 'Fez', iataCode: 'FEZ', countryCode: 'MA', isServed: true },
    { nameKo: '카사블랑카', nameEn: 'Casablanca', iataCode: 'CMN', countryCode: 'MA', isServed: true },
    { nameKo: '셰프샤우엔', nameEn: '셰프샤우엔', iataCode: null, countryCode: 'MA', isServed: true },
    { nameKo: '라바트', nameEn: 'Rabat', iataCode: 'RBA', countryCode: 'MA', isServed: true },
    { nameKo: '메르주가', nameEn: '메르주가', iataCode: null, countryCode: 'MA', isServed: true },
    { nameKo: '에사우이라', nameEn: 'Essaouira', iataCode: 'ESU', countryCode: 'MA', isServed: true },
    { nameKo: '아가디르', nameEn: 'Agadir', iataCode: 'AGA', countryCode: 'MA', isServed: true },
    { nameKo: '아바나', nameEn: '아바나', iataCode: null, countryCode: 'CU', isServed: true },
    { nameKo: '트리니다드', nameEn: 'Trinidad', iataCode: null, countryCode: 'CU', isServed: true },
    { nameKo: '바라데로', nameEn: 'Varadero', iataCode: 'VRA', countryCode: 'CU', isServed: true },
    { nameKo: '산티아고데쿠바', nameEn: 'Santiago de Cuba', iataCode: 'SCU', countryCode: 'CU', isServed: true },
    { nameKo: '비냘레스', nameEn: 'Vinales', iataCode: null, countryCode: 'CU', isServed: true },
    { nameKo: '시엔푸에고스', nameEn: 'Cienfuegos', iataCode: 'CFG', countryCode: 'CU', isServed: true },
    { nameKo: '비슈케크', nameEn: 'Bishkek', iataCode: 'FRU', countryCode: 'KG', isServed: true },
    { nameKo: '오시', nameEn: 'Osh', iataCode: 'OSS', countryCode: 'KG', isServed: true },
    { nameKo: '이식쿨호수', nameEn: '이식쿨호수', iataCode: null, countryCode: 'KG', isServed: true },
    { nameKo: '카라콜', nameEn: 'Karakol', iataCode: null, countryCode: 'KG', isServed: true },
    { nameKo: '아르슬란밥', nameEn: '아르슬란밥', iataCode: null, countryCode: 'KG', isServed: true },
    { nameKo: '나린', nameEn: '나린', iataCode: null, countryCode: 'KG', isServed: true },
    { nameKo: '헬싱키', nameEn: 'Helsinki', iataCode: 'HEL', countryCode: 'FI', isServed: true },
    { nameKo: '로바니에미', nameEn: 'Rovaniemi', iataCode: 'RVN', countryCode: 'FI', isServed: true },
    { nameKo: '루카', nameEn: '루카', iataCode: null, countryCode: 'FI', isServed: true },
    { nameKo: '이발로', nameEn: '이발로', iataCode: null, countryCode: 'FI', isServed: true },
    { nameKo: '탐페레', nameEn: 'Tampere', iataCode: 'TMP', countryCode: 'FI', isServed: true },
    { nameKo: '투르쿠', nameEn: 'Turku', iataCode: 'TKU', countryCode: 'FI', isServed: true },
    { nameKo: '포르보', nameEn: '포르보', iataCode: null, countryCode: 'FI', isServed: true },
    { nameKo: '오울루', nameEn: 'Oulu', iataCode: 'OUL', countryCode: 'FI', isServed: true },
  ]

  for (const city of cities) {
    const countryId = countryIdMap[city.countryCode]
    if (!countryId) { skipped++; continue }
    const exists = await prisma.city.findFirst({
      where: { nameKo: city.nameKo, countryId },
    })
    if (exists) { skipped++; continue }
    await prisma.city.create({
      data: {
        nameKo: city.nameKo,
        nameEn: city.nameEn,
        iataCode: city.iataCode,
        countryId,
        isServed: city.isServed,
      },
    })
    inserted++
  }

  console.log(`✅ 도시 삽입: ${inserted}개 / 스킵(중복): ${skipped}개`)
  console.log('🎉 시드 완료!')
}

main().catch(console.error).finally(() => prisma.$disconnect())